# Generated by Django 5.0.3 on 2026-01-24 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('exam_type', models.CharField(choices=[('PBE', 'PBE'), ('CBE', 'CBE')], default='PBE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('max_students', models.IntegerField(default=0)),
                ('min_courses', models.IntegerField(default=0)),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='2024/2025', max_length=200, unique=True)),
                ('semester', models.CharField(default='1st Semester', max_length=100)),
                ('has_timetable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('size', models.IntegerField()),
                ('courses', models.ManyToManyField(related_name='courses', to='ems.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_dep', to='ems.department')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15, null=True)),
                ('period', models.CharField(max_length=2, null=True)),
                ('items', models.ManyToManyField(to='ems.distributionitem')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('matric_no', models.CharField(db_index=True, max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.class')),
            ],
        ),
        migrations.CreateModel(
            name='SeatArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=50)),
                ('date', models.DateField()),
                ('seat_number', models.IntegerField(blank=True, null=True)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.course')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.hall')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.student')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=50)),
                ('date', models.DateField()),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_class', to='ems.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_course', to='ems.course')),
            ],
        ),
        migrations.AddField(
            model_name='distributionitem',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.timetable'),
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('job_type', models.CharField(choices=[('timetable', 'Timetable Generation'), ('distribution', 'Distribution Generation'), ('allocation', 'Seat Allocation')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_id'], name='ems_backgro_job_id_6ffc21_idx'), models.Index(fields=['created_by', '-started_at'], name='ems_backgro_created_dbbfb6_idx'), models.Index(fields=['status', '-started_at'], name='ems_backgro_status_948542_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department', 'level'], name='ems_student_departm_b2b1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['matric_no', 'department'], name='ems_student_matric__45934b_idx'),
        ),
    ]
