# Generated by Django 5.0.3 on 2026-03-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_alter_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_no',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
