# Generated by Django 5.0.3 on 2026-05-13 13:11

import django.db.models.deletion
import ems.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_faculty_department_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='exam_period',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], default='', max_length=2),
        ),
        migrations.CreateModel(
            name='GenerationConstraints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbe_autosplit_threshold', models.PositiveIntegerField(default=9000)),
                ('cbe_fullday_threshold', models.PositiveIntegerField(default=4500)),
                ('cbe_daily_cap_per_period', models.PositiveIntegerField(default=4500)),
                ('pbe_hall_utilization', models.DecimalField(decimal_places=2, default=0.9, max_digits=3)),
                ('excluded_weekdays', models.JSONField(default=ems.models._default_excluded_weekdays)),
                ('remainder_merge_threshold', models.PositiveIntegerField(default=5)),
                ('adjacency_mode', models.CharField(choices=[('8-dir', '8-direction (strict)'), ('4-dir', '4-direction (cardinal only)'), ('off', 'Off')], default='8-dir', max_length=8)),
                ('manual_override_adjacency_enforced', models.BooleanField(default=False)),
                ('placement_attempts_pass2', models.PositiveIntegerField(default=100)),
                ('placement_attempts_pass3', models.PositiveIntegerField(default=300)),
                ('placement_attempts_pass4', models.PositiveIntegerField(default=500)),
                ('placement_success_threshold_pct', models.PositiveIntegerField(default=60)),
                ('seating_pattern_order', models.JSONField(default=ems.models._default_seating_patterns)),
                ('configured_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generation constraints',
                'verbose_name_plural': 'Generation constraints',
            },
        ),
    ]
