# Generated by Django 5.0.3 on 2026-05-13 13:39

import ems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_class_exam_period_generationconstraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='exam_period',
        ),
        migrations.AddField(
            model_name='generationconstraints',
            name='class_period_overrides',
            field=models.JSONField(default=ems.models._default_class_period_overrides),
        ),
    ]
