# Generated by Django 5.0.3 on 2026-05-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_remove_class_exam_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationconstraints',
            name='adjacency_mode',
        ),
        migrations.RemoveField(
            model_name='generationconstraints',
            name='manual_override_adjacency_enforced',
        ),
        migrations.RemoveField(
            model_name='generationconstraints',
            name='placement_attempts_pass2',
        ),
        migrations.RemoveField(
            model_name='generationconstraints',
            name='placement_attempts_pass3',
        ),
        migrations.RemoveField(
            model_name='generationconstraints',
            name='placement_attempts_pass4',
        ),
        migrations.RemoveField(
            model_name='generationconstraints',
            name='seating_pattern_order',
        ),
    ]
