# Generated by Django 5.0.3 on 2026-05-13 14:27

import ems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0007_remove_generationconstraints_adjacency_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationconstraints',
            name='cbe_faculty_groups',
            field=models.JSONField(default=ems.models._default_cbe_faculty_groups),
        ),
        migrations.AddField(
            model_name='generationconstraints',
            name='cbe_group_count',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
