# Generated by Django 5.0.3 on 2026-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0008_generationconstraints_cbe_faculty_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationconstraints',
            name='seat_pattern',
            field=models.CharField(choices=[('checkerboard', 'Checkerboard (strict spacing, ~50% capacity)'), ('sequential', 'Sequential (full capacity, adjacency-only spacing)')], default='checkerboard', max_length=20),
        ),
    ]
