# Generated by Django 5.0.3 on 2026-06-04 14:10

from django.db import migrations, models


def backfill_super_admin(apps, schema_editor):
    """Existing admins keep full access: every is_staff user becomes a Super Admin."""
    User = apps.get_model('ems', 'User')
    User.objects.filter(is_staff=True).update(role='SA')


def clear_roles(apps, schema_editor):
    User = apps.get_model('ems', 'User')
    User.objects.update(role=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0009_generationconstraints_seat_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SA', 'Super Admin'), ('DO', 'Data Officer'), ('FO', 'Faculty Officer'), ('ECM', 'Exam Committee Member')], max_length=4, null=True),
        ),
        migrations.RunPython(backfill_super_admin, clear_roles),
    ]
