# Generated by Django 5.0.3 on 2026-06-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0010_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='exam_heading',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='institution_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='institution_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='institution_short_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
