# Generated by Django 5.0.3 on 2026-06-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0011_systemsettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
