# Generated by Django 5.0.3 on 2026-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0012_systemsettings_brand_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='visa_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
