# Generated by Django 6.1.1 on 2026-09-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0015_class_is_active_timetable_planned_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='seating_rule',
            field=models.CharField(choices=[('strict', 'Strict'), ('relaxed', 'Relaxed')], default='strict', max_length=10),
        ),
    ]
