# Generated by Django 5.0.3 on 2026-09-28 16:57

import ems.cloudinary_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0017_clean_matric_and_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=ems.cloudinary_storage.select_logo_storage, upload_to='branding/'),
        ),
    ]
