# Generated by Django 5.0.3 on 2026-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0018_systemsettings_logo_cloudinary'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='distribution',
            index=models.Index(fields=['date', 'period'], name='ems_distrib_date_e9ecdf_idx'),
        ),
        migrations.AddIndex(
            model_name='seatarrangement',
            index=models.Index(fields=['date', 'period', 'hall'], name='ems_seatarr_date_bb3143_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['date', 'period'], name='ems_timetab_date_657c06_idx'),
        ),
    ]
