# Generated by Django 5.0.3 on 2026-09-29 15:28

import ems.models
from django.db import migrations, models


def fill_groups(apps, schema_editor):
    """Every existing hall's group from its name ("BE 3" -> "BE")."""
    from ems.halls import group_from_name

    Hall = apps.get_model("ems", "Hall")
    for hall in Hall.objects.all():
        hall.group = group_from_name(hall.name)
        hall.save(update_fields=["group"])


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0020_hall_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationconstraints',
            name='hall_course_limits',
            field=models.JSONField(default=ems.models._default_hall_course_limits),
        ),
        migrations.AddField(
            model_name='generationconstraints',
            name='hall_group_order',
            field=models.JSONField(default=ems.models._default_hall_group_order),
        ),
        migrations.AddField(
            model_name='hall',
            name='group',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.RunPython(fill_groups, migrations.RunPython.noop),
    ]
