# Generated by Django 5.0.3 on 2026-09-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0021_hall_groups_and_course_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='seat_order',
            field=models.CharField(choices=[('rows', 'Row by row, left to right'), ('rows_rtl', 'Row by row, right to left'), ('snake', 'Snake, first row left to right'), ('snake_rtl', 'Snake, first row right to left'), ('columns', 'Column by column, front to back'), ('columns_snake', 'Snake down and up the columns')], default='rows', max_length=20),
        ),
    ]
