# Generated by Django 5.0.3 on 2026-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0022_hall_seat_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
