# Generated by Django 5.0.3 on 2026-10-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0023_hall_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationconstraints',
            name='small_course_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
